[case]
name = ""
simulator = "beach"
launcher = "default"
description = ""

[params]
# "sim.dt" = 1.0e-6
# "sim.max_step" = 1000
# "environment.electron_density" = 1.0e12

[job]
partition = ""
nodes = 1
ntasks = 1
walltime = "01:00:00"
