[case]
name = ""
simulator = "emses"
launcher = "default"
description = ""

[params]
# "tmgrid.nx" = 64
# "tmgrid.ny" = 64
# "tmgrid.nz" = 64
# "tmgrid.dt" = 1.0
# "jobcon.nstep" = 10000

[job]
partition = ""
nodes = 1
ntasks = 1
walltime = "01:00:00"
