# cmaphor (Fujitsu PRIMEHPC / camphor3)
# Resource style: --rsc p=N:t=T:c=C

[launcher]
type = "srun"
use_slurm_ntasks = true
resource_style = "rsc"
modules = [
    "intel/2023.2",
    "intelmpi/2023.2",
]
stdout = "stdout.%J.log"
stderr = "stderr.%J.log"

[simulator.emses]
modules = [
    "hdf5/1.12.2_intel-2023.2-impi",
    "fftw/3.3.10_intel-2022.3-impi",
]

[simulator.beach]
# No additional modules needed
